### PR TITLE
feat: Add Fixed parameter for `network-zones`

### LINKED ISSUE #1356: Monaco 2.10.0 - incorrect order deploying network zones
During deployment Monaco tries to deploy management:network-zone before builtin:networkzones
it fails on first run with following message:
`Failed to send HTTP request: (HTTP 400)!     Response was: Not allowed because network zones are disabled`
it is successful on rerun

**How to reproduce**
- new environment with network zones disabled
- management:network-zone set to enable in /builtinnetworkzones/config.yaml+ json
- a network zone described network-zone/config.yaml + json

**Expected behavior**
monaco turns on network zones setting and sets them up

Monaco 2.10.0

### PR DESCRIPTION
**Pull request by warber**
#### What this PR does / Why we need it:
When both, `builtin:networkzones` and `network-zone` apis are deployed, we need to make sure the settings 2.0 object is deployed first. Hence we introduce a fixed parameter as soon as we see both config appearing in a config set.

#### Special notes for your reviewer:
First commit fixes the problem, second commit reduces cognitive complexity of that code area in general.

#### Does this PR introduce a user-facing change?
fixes #1356

### CODE REVIEW

File: pkg/project/v2/project_loader.go [hunk 1]
```diff
@@ -191,22 +189,46 @@ func loadProject(fs afero.Fs, context ProjectLoaderContext, projectDefinition ma
...
+	for _, c := range configs {
+		if c.Coordinate.Type == api.NetworkZone {
+			networkZones = append(networkZones, c)
+		}
+		if c.Coordinate.Type == "builtin:networkzones" {
+			networkZoneEnabled = c
+			networkZoneEnabledFound = true
+		}
+	}
+	// if we've found "networkzones" and "builtin:networkzones" settings 2.0 objects, then insert a fixed parameter.
```
Comment (UnseenWizzard) [inline pkg/project/v2/project_loader.go:219]: nit: this comment feels somewhat redundant, you have extensive description before the block, and that this loop adds the ref param is IMO clear from code.

File: pkg/project/v2/project_loader.go [hunk 2]
```diff
@@ -191,22 +189,46 @@ func loadProject(fs afero.Fs, context ProjectLoaderContext, projectDefinition ma
...
 					"parameter to another web-application config", api.KeyUserActionsWeb, c.Coordinate.ConfigId))
 			}
 		}
 	}
-
 	if errors != nil {
 		return Project{}, errors
 	}
 
+	// Network zone API configs have a hard dependency on the "builtin:networkzones" setting 2.0 config
```
Comment (UnseenWizzard) [inline pkg/project/v2/project_loader.go:203]: Please describe WHY we actually need to do this, currently this extensive doc comment mainly tells me that there's some "dependency" and WHAT the code below does.

What I get from the code and variable naming, the setting is for (de)activating networkzones in general, so it needs to be configured for any zones (as their API calls would fail, if the setting is off I assume?)? 
If that's correct, the code actually tells me more about the WHY than 3 lines of comments ;)

File: pkg/project/v2/project_loader.go [hunk 3]
```diff
@@ -182,28 +182,24 @@ func loadProject(fs afero.Fs, context ProjectLoaderContext, projectDefinition ma
...
+
+	return Project{
+		Id:           projectDefinition.Name,
+		GroupId:      projectDefinition.Group,
+		Configs:      toConfigMap(configs),
+		Dependencies: toDependenciesMap(projectDefinition.Name, configs),
+	}, nil
+}
+
+func insertFixedParameters(configs []config.Config) {
```
Comment (UnseenWizzard) [inline pkg/project/v2/project_loader.go:202]: I assume this is named with the intention, that it COULD do more things than just adding the one fixed reference for network zones in the future? 
IMO it can be changed to that if it ever happens - for now it'd be nicer to read with a clear name and by moving the documentation of WHY from comments inside the function to one on the function itself. 
Also a note that it modifies the configs it's given might not hurt

**Review by UnseenWizzard — APPROVED** [review]
Functionality looks good (if I understood correctly why we do this - see comments)
Comments are basically nitpicks on naming and documentation, and could be deferred if this fix needs to ship

**Review by UnseenWizzard — APPROVED** [review]
